/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import Controlador.EstudianteControlador;
import Controlador.EntradaSalidaControlador;
import Controlador.BotellonesControlador;
import Controlador.CocinaControlador;



public class EditarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form EditarEstudiantebtn
     */
    public EditarEstudiante() {
        initComponents();
    }
    private Timer timer;
    private String lastQuery = "";
    private int FiaSeleccionada;
    EstudianteControlador estudianteControlador = new EstudianteControlador();
    EntradaSalidaControlador entradaSalidaControlador = new EntradaSalidaControlador();
    BotellonesControlador botellonesControlador = new BotellonesControlador();
    CocinaControlador cocinaControlador = new CocinaControlador();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        RegistrarEstudianteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        HistorialCocinaBnt = new javax.swing.JButton();
        HistorialEntradaSalida = new javax.swing.JButton();
        InformeDeActividadBtn = new javax.swing.JButton();
        NotificacionesBotellonesbtn = new javax.swing.JButton();
        HistorialBotellonesbtn = new javax.swing.JButton();
        RetirarEstudiantesbtn = new javax.swing.JButton();
        VerEstudianteBtn = new javax.swing.JButton();
        EditarEstudiantebtn2 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MatriculaRegistroEditar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CargarEstudiantebtn = new javax.swing.JButton();
        NombresRegistroEditar = new javax.swing.JTextField();
        NumeroRegistroEditar = new javax.swing.JTextField();
        ApellidosRegistroEditar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ModuloRegistroEditar = new javax.swing.JComboBox<>();
        HabitacionRegistroEditar = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEstudiantesEditar = new javax.swing.JTable();
        BuscarMatriculaFieldEditar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        GuardarEstudiantebtn = new javax.swing.JButton();
        MatriculaRegistroEditarNew = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 55, 133));

        RegistrarEstudianteBtn.setBackground(new java.awt.Color(20, 101, 187));
        RegistrarEstudianteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistrarEstudianteBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarEstudianteBtn.setText("Registrar Estudiante");
        RegistrarEstudianteBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(20, 101, 187)));
        RegistrarEstudianteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarEstudianteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarEstudianteBtnMouseExited(evt);
            }
        });
        RegistrarEstudianteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEstudianteBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ControlAdmin");

        HistorialCocinaBnt.setBackground(new java.awt.Color(20, 101, 187));
        HistorialCocinaBnt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HistorialCocinaBnt.setForeground(new java.awt.Color(255, 255, 255));
        HistorialCocinaBnt.setText("Historial Cocina");
        HistorialCocinaBnt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(20, 101, 187)));
        HistorialCocinaBnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistorialCocinaBntMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HistorialCocinaBntMouseExited(evt);
            }
        });
        HistorialCocinaBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialCocinaBntActionPerformed(evt);
            }
        });

        HistorialEntradaSalida.setBackground(new java.awt.Color(20, 101, 187));
        HistorialEntradaSalida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HistorialEntradaSalida.setForeground(new java.awt.Color(255, 255, 255));
        HistorialEntradaSalida.setText("Historial Entrada/salida");
        HistorialEntradaSalida.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(20, 101, 187)));
        HistorialEntradaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistorialEntradaSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HistorialEntradaSalidaMouseExited(evt);
            }
        });
        HistorialEntradaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialEntradaSalidaActionPerformed(evt);
            }
        });

        InformeDeActividadBtn.setBackground(new java.awt.Color(20, 101, 187));
        InformeDeActividadBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InformeDeActividadBtn.setForeground(new java.awt.Color(255, 255, 255));
        InformeDeActividadBtn.setText("Informe De Actividad");
        InformeDeActividadBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(20, 101, 187)));
        InformeDeActividadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InformeDeActividadBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InformeDeActividadBtnMouseExited(evt);
            }
        });
        InformeDeActividadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeDeActividadBtnActionPerformed(evt);
            }
        });

        NotificacionesBotellonesbtn.setBackground(new java.awt.Color(20, 101, 187));
        NotificacionesBotellonesbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NotificacionesBotellonesbtn.setForeground(new java.awt.Color(255, 255, 255));
        NotificacionesBotellonesbtn.setText("Notificaciones Botellones");
        NotificacionesBotellonesbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(20, 101, 187)));
        NotificacionesBotellonesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NotificacionesBotellonesbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NotificacionesBotellonesbtnMouseExited(evt);
            }
        });
        NotificacionesBotellonesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificacionesBotellonesbtnActionPerformed(evt);
            }
        });

        HistorialBotellonesbtn.setBackground(new java.awt.Color(20, 101, 187));
        HistorialBotellonesbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HistorialBotellonesbtn.setForeground(new java.awt.Color(255, 255, 255));
        HistorialBotellonesbtn.setText("Historial Botellones");
        HistorialBotellonesbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(20, 101, 187)));
        HistorialBotellonesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistorialBotellonesbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HistorialBotellonesbtnMouseExited(evt);
            }
        });
        HistorialBotellonesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialBotellonesbtnActionPerformed(evt);
            }
        });

        RetirarEstudiantesbtn.setBackground(new java.awt.Color(20, 101, 187));
        RetirarEstudiantesbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RetirarEstudiantesbtn.setForeground(new java.awt.Color(255, 255, 255));
        RetirarEstudiantesbtn.setText("Retirar Estudiantes");
        RetirarEstudiantesbtn.setBorder(null);
        RetirarEstudiantesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RetirarEstudiantesbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RetirarEstudiantesbtnMouseExited(evt);
            }
        });
        RetirarEstudiantesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarEstudiantesbtnActionPerformed(evt);
            }
        });

        VerEstudianteBtn.setBackground(new java.awt.Color(20, 101, 187));
        VerEstudianteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VerEstudianteBtn.setForeground(new java.awt.Color(255, 255, 255));
        VerEstudianteBtn.setText("Ver Estudiante");
        VerEstudianteBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(20, 101, 187)));
        VerEstudianteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerEstudianteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerEstudianteBtnMouseExited(evt);
            }
        });
        VerEstudianteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEstudianteBtnActionPerformed(evt);
            }
        });

        EditarEstudiantebtn2.setBackground(new java.awt.Color(51, 153, 255));
        EditarEstudiantebtn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EditarEstudiantebtn2.setForeground(new java.awt.Color(255, 255, 255));
        EditarEstudiantebtn2.setText("Editar Estudiante");
        EditarEstudiantebtn2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(20, 101, 187)));
        EditarEstudiantebtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarEstudiantebtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarEstudiantebtn2MouseExited(evt);
            }
        });
        EditarEstudiantebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEstudiantebtn2ActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrarEstudianteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HistorialCocinaBnt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InformeDeActividadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HistorialBotellonesbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NotificacionesBotellonesbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
            .addComponent(RetirarEstudiantesbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VerEstudianteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HistorialEntradaSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EditarEstudiantebtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(VerEstudianteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RegistrarEstudianteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(HistorialCocinaBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(HistorialEntradaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InformeDeActividadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(HistorialBotellonesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(NotificacionesBotellonesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(EditarEstudiantebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RetirarEstudiantesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        jPanel4.setBackground(new java.awt.Color(30, 30, 30));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setEnabled(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editar Estudiante");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 41));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 110, -1));

        MatriculaRegistroEditar.setBackground(new java.awt.Color(30, 30, 30));
        MatriculaRegistroEditar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MatriculaRegistroEditar.setForeground(new java.awt.Color(255, 255, 255));
        MatriculaRegistroEditar.setBorder(null);
        MatriculaRegistroEditar.setEnabled(false);
        MatriculaRegistroEditar.setSelectionColor(new java.awt.Color(20, 101, 187));
        MatriculaRegistroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaRegistroEditarActionPerformed(evt);
            }
        });
        MatriculaRegistroEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MatriculaRegistroEditarKeyTyped(evt);
            }
        });
        jPanel4.add(MatriculaRegistroEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 330, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombres");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Matricula");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Modulo");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 100, 20));

        CargarEstudiantebtn.setBackground(new java.awt.Color(30, 30, 30));
        CargarEstudiantebtn.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        CargarEstudiantebtn.setForeground(new java.awt.Color(255, 255, 255));
        CargarEstudiantebtn.setText("Cargar");
        CargarEstudiantebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        CargarEstudiantebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarEstudiantebtnActionPerformed(evt);
            }
        });
        jPanel4.add(CargarEstudiantebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 150, 50));

        NombresRegistroEditar.setBackground(new java.awt.Color(30, 30, 30));
        NombresRegistroEditar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        NombresRegistroEditar.setForeground(new java.awt.Color(255, 255, 255));
        NombresRegistroEditar.setBorder(null);
        jPanel4.add(NombresRegistroEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 320, 30));

        NumeroRegistroEditar.setBackground(new java.awt.Color(30, 30, 30));
        NumeroRegistroEditar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        NumeroRegistroEditar.setForeground(new java.awt.Color(255, 255, 255));
        NumeroRegistroEditar.setBorder(null);
        NumeroRegistroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroRegistroEditarActionPerformed(evt);
            }
        });
        jPanel4.add(NumeroRegistroEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 244, 320, 30));

        ApellidosRegistroEditar.setBackground(new java.awt.Color(30, 30, 30));
        ApellidosRegistroEditar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ApellidosRegistroEditar.setForeground(new java.awt.Color(255, 255, 255));
        ApellidosRegistroEditar.setBorder(null);
        ApellidosRegistroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosRegistroEditarActionPerformed(evt);
            }
        });
        jPanel4.add(ApellidosRegistroEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 330, 35));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Habitacion");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 138, 20));

        ModuloRegistroEditar.setBackground(new java.awt.Color(255, 255, 255));
        ModuloRegistroEditar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ModuloRegistroEditar.setForeground(new java.awt.Color(0, 0, 0));
        ModuloRegistroEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28" }));
        ModuloRegistroEditar.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ModuloRegistroEditarPopupMenuWillBecomeVisible(evt);
            }
        });
        ModuloRegistroEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModuloRegistroEditarMousePressed(evt);
            }
        });
        ModuloRegistroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuloRegistroEditarActionPerformed(evt);
            }
        });
        ModuloRegistroEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModuloRegistroEditarKeyPressed(evt);
            }
        });
        jPanel4.add(ModuloRegistroEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 330, 34));

        HabitacionRegistroEditar.setBackground(new java.awt.Color(255, 255, 255));
        HabitacionRegistroEditar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        HabitacionRegistroEditar.setForeground(new java.awt.Color(0, 0, 0));
        HabitacionRegistroEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "A", "B", "C", "D", "E" }));
        HabitacionRegistroEditar.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                HabitacionRegistroEditarPopupMenuWillBecomeVisible(evt);
            }
        });
        HabitacionRegistroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitacionRegistroEditarActionPerformed(evt);
            }
        });
        jPanel4.add(HabitacionRegistroEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 330, 37));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 330, -1));

        jSeparator2.setBackground(java.awt.Color.white);
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 170, 330, -1));

        jSeparator3.setBackground(java.awt.Color.white);
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 330, -1));

        jSeparator4.setBackground(java.awt.Color.white);
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 280, 330, -1));

        TablaEstudiantesEditar.setBackground(new java.awt.Color(255, 255, 255));
        TablaEstudiantesEditar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        TablaEstudiantesEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TablaEstudiantesEditar.setForeground(new java.awt.Color(0, 0, 0));
        TablaEstudiantesEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre", "Apellido", "Numero ", "Modulo", "Habitacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaEstudiantesEditar.setToolTipText("Listado de contactos");
        TablaEstudiantesEditar.setGridColor(new java.awt.Color(30, 30, 30));
        TablaEstudiantesEditar.setRowHeight(30);
        TablaEstudiantesEditar.getTableHeader().setResizingAllowed(false);
        TablaEstudiantesEditar.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaEstudiantesEditar);
        if (TablaEstudiantesEditar.getColumnModel().getColumnCount() > 0) {
            TablaEstudiantesEditar.getColumnModel().getColumn(0).setResizable(false);
            TablaEstudiantesEditar.getColumnModel().getColumn(1).setResizable(false);
            TablaEstudiantesEditar.getColumnModel().getColumn(2).setResizable(false);
            TablaEstudiantesEditar.getColumnModel().getColumn(3).setResizable(false);
            TablaEstudiantesEditar.getColumnModel().getColumn(4).setResizable(false);
            TablaEstudiantesEditar.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 525, 800, 110));

        BuscarMatriculaFieldEditar.setBackground(new java.awt.Color(30, 30, 30));
        BuscarMatriculaFieldEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BuscarMatriculaFieldEditar.setForeground(new java.awt.Color(255, 255, 255));
        BuscarMatriculaFieldEditar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(30, 30, 30)));
        BuscarMatriculaFieldEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMatriculaFieldEditarActionPerformed(evt);
            }
        });
        BuscarMatriculaFieldEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarMatriculaFieldEditarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarMatriculaFieldEditarKeyTyped(evt);
            }
        });
        jPanel4.add(BuscarMatriculaFieldEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 208, 30));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 208, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar Matricula");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 393, 790, -1));

        GuardarEstudiantebtn.setBackground(new java.awt.Color(30, 30, 30));
        GuardarEstudiantebtn.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        GuardarEstudiantebtn.setForeground(new java.awt.Color(255, 255, 255));
        GuardarEstudiantebtn.setText("Guardar");
        GuardarEstudiantebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        GuardarEstudiantebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEstudiantebtnActionPerformed(evt);
            }
        });
        jPanel4.add(GuardarEstudiantebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 150, 50));

        MatriculaRegistroEditarNew.setBackground(new java.awt.Color(30, 30, 30));
        MatriculaRegistroEditarNew.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MatriculaRegistroEditarNew.setForeground(new java.awt.Color(255, 255, 255));
        MatriculaRegistroEditarNew.setBorder(null);
        MatriculaRegistroEditarNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaRegistroEditarNewActionPerformed(evt);
            }
        });
        MatriculaRegistroEditarNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MatriculaRegistroEditarNewKeyTyped(evt);
            }
        });
        jPanel4.add(MatriculaRegistroEditarNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 50, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 0, 940, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerEstudianteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEstudianteBtnActionPerformed

        VerEstudiantes verEstudiantes = new VerEstudiantes();
        verEstudiantes.setVisible(true);
        this.dispose();
        verEstudiantes.setLocationRelativeTo(null);

        DefaultTableModel modelo = (DefaultTableModel) verEstudiantes.TablaEstudiantes.getModel();
        estudianteControlador.MostrarEstudiante(modelo);
    }//GEN-LAST:event_VerEstudianteBtnActionPerformed

    private void RetirarEstudiantesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarEstudiantesbtnActionPerformed
        RetirarEstudiante retirar = new RetirarEstudiante();
        
        retirar.setVisible(true);
        this.dispose();
        retirar.setLocationRelativeTo(null);

        DefaultTableModel modelo = (DefaultTableModel) retirar.TablaEstudiantesRetirar.getModel();
        estudianteControlador.MostrarEstudiante(modelo);
    }//GEN-LAST:event_RetirarEstudiantesbtnActionPerformed

    private void HistorialBotellonesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialBotellonesbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistorialBotellonesbtnActionPerformed

    private void NotificacionesBotellonesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificacionesBotellonesbtnActionPerformed
        NotificacionesBotellones notificacionesBotellones = new NotificacionesBotellones();

        DefaultTableModel modelo = (DefaultTableModel) notificacionesBotellones.NotificacionesBotetellonesTabla.getModel(); 
        botellonesControlador.NotificaionesBotellones(modelo);
        
        notificacionesBotellones.setVisible(true);
        this.dispose();
        notificacionesBotellones.setLocationRelativeTo(null);
    }//GEN-LAST:event_NotificacionesBotellonesbtnActionPerformed

    private void InformeDeActividadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeDeActividadBtnActionPerformed
        InformeDeActividad informe = new InformeDeActividad();
        informe.setVisible(true);
        this.dispose();
        informe.setLocationRelativeTo(null);
    }//GEN-LAST:event_InformeDeActividadBtnActionPerformed

    private void HistorialEntradaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialEntradaSalidaActionPerformed
        HistorialEntradaSalida historialEntradaSalida = new HistorialEntradaSalida();

        DefaultTableModel modelo = (DefaultTableModel) historialEntradaSalida.TablaHitorialEntradaSalida.getModel();
        entradaSalidaControlador.HistorialEntradaSalida(modelo);

        historialEntradaSalida.setVisible(true);
        this.dispose();
        historialEntradaSalida.setLocationRelativeTo(null);
    }//GEN-LAST:event_HistorialEntradaSalidaActionPerformed

    private void HistorialCocinaBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialCocinaBntActionPerformed
        HistorialCocina Cocina = new HistorialCocina();
        DefaultTableModel modelo = (DefaultTableModel) Cocina.HistorialCocinaTable.getModel();
        cocinaControlador.HistorialUsoCocina(modelo);

        Cocina.setVisible(true);
        this.dispose();
        Cocina.setLocationRelativeTo(null);
    }//GEN-LAST:event_HistorialCocinaBntActionPerformed

    private void RegistrarEstudianteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEstudianteBtnActionPerformed
        RegistrarEstudiante registrarEstudiante = new RegistrarEstudiante();
        registrarEstudiante.setVisible(true);
        this.dispose();
        registrarEstudiante.setLocationRelativeTo(null);
    }//GEN-LAST:event_RegistrarEstudianteBtnActionPerformed

    private void RegistrarEstudianteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarEstudianteBtnMouseExited
        RegistrarEstudianteBtn.setBackground(new Color(20,101,187));
    }//GEN-LAST:event_RegistrarEstudianteBtnMouseExited

    private void MatriculaRegistroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaRegistroEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculaRegistroEditarActionPerformed

    private void MatriculaRegistroEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MatriculaRegistroEditarKeyTyped
        if(MatriculaRegistroEditar.getText().length() >=8){
            evt.consume();
        }

        char key = evt.getKeyChar();
        if(!Character.isDigit(key)) {
            evt.consume();

        }
    }//GEN-LAST:event_MatriculaRegistroEditarKeyTyped

    private void CargarEstudiantebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarEstudiantebtnActionPerformed
        
        FiaSeleccionada = TablaEstudiantesEditar.getSelectedRow();

        if (FiaSeleccionada == -1) {
            // mostrar un mensaje de advertencia si no hay fila seleccionada
            JOptionPane.showMessageDialog(null, "Por favor, selecciona un estudiante de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return; // Salir del método
        }

        MatriculaRegistroEditar.setText(TablaEstudiantesEditar.getValueAt(FiaSeleccionada, 0).toString());
        NombresRegistroEditar.setText(TablaEstudiantesEditar.getValueAt(FiaSeleccionada, 1).toString());
        ApellidosRegistroEditar.setText(TablaEstudiantesEditar.getValueAt(FiaSeleccionada, 2).toString());
        NumeroRegistroEditar.setText(TablaEstudiantesEditar.getValueAt(FiaSeleccionada, 3).toString());
        ModuloRegistroEditar.setSelectedItem(TablaEstudiantesEditar.getValueAt(FiaSeleccionada, 4).toString());
        HabitacionRegistroEditar.setSelectedItem(TablaEstudiantesEditar.getValueAt(FiaSeleccionada, 5));
    }//GEN-LAST:event_CargarEstudiantebtnActionPerformed

    private void NumeroRegistroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroRegistroEditarActionPerformed
    }//GEN-LAST:event_NumeroRegistroEditarActionPerformed

    private void ApellidosRegistroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosRegistroEditarActionPerformed
    }//GEN-LAST:event_ApellidosRegistroEditarActionPerformed

    private void ModuloRegistroEditarPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ModuloRegistroEditarPopupMenuWillBecomeVisible

    }//GEN-LAST:event_ModuloRegistroEditarPopupMenuWillBecomeVisible

    private void ModuloRegistroEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModuloRegistroEditarMousePressed

    }//GEN-LAST:event_ModuloRegistroEditarMousePressed

    private void ModuloRegistroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuloRegistroEditarActionPerformed
        
    }//GEN-LAST:event_ModuloRegistroEditarActionPerformed

    private void ModuloRegistroEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModuloRegistroEditarKeyPressed
       
    }//GEN-LAST:event_ModuloRegistroEditarKeyPressed

    private void HabitacionRegistroEditarPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_HabitacionRegistroEditarPopupMenuWillBecomeVisible

    }//GEN-LAST:event_HabitacionRegistroEditarPopupMenuWillBecomeVisible

    private void HabitacionRegistroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitacionRegistroEditarActionPerformed
        
    }//GEN-LAST:event_HabitacionRegistroEditarActionPerformed

    private void BuscarMatriculaFieldEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMatriculaFieldEditarActionPerformed
        
    }//GEN-LAST:event_BuscarMatriculaFieldEditarActionPerformed

    private void BuscarMatriculaFieldEditarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarMatriculaFieldEditarKeyReleased
       String matricula = BuscarMatriculaFieldEditar.getText().trim();
    if (timer != null) {
        timer.stop();
    }
    if (!matricula.isEmpty()) {

        timer = new Timer(400, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!matricula.equals(lastQuery)) {
                    DefaultTableModel modelo = (DefaultTableModel) TablaEstudiantesEditar.getModel();
                    try {
                        estudianteControlador.BuscarEstudianteEditar(modelo, matricula); 
                        lastQuery = matricula;
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(VerEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    } else {
        // si el campo está vacío, mostrar todos los estudiantes
        DefaultTableModel modelo = (DefaultTableModel) TablaEstudiantesEditar.getModel();
        try {
            estudianteControlador.BuscarEstudianteEditar(modelo, matricula); 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VerEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    }//GEN-LAST:event_BuscarMatriculaFieldEditarKeyReleased

    
    private void BuscarMatriculaFieldEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarMatriculaFieldEditarKeyTyped

        if(BuscarMatriculaFieldEditar.getText().length() >=8){
            evt.consume();
        }

        char key = evt.getKeyChar();
        if(!Character.isDigit(key)) {
            evt.consume();

        }

    }//GEN-LAST:event_BuscarMatriculaFieldEditarKeyTyped

    private void GuardarEstudiantebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEstudiantebtnActionPerformed
        
        // validar los campos
        if (MatriculaRegistroEditar.getText().trim().isEmpty() || 
            NombresRegistroEditar.getText().trim().isEmpty() || 
            ApellidosRegistroEditar.getText().trim().isEmpty() || 
            NumeroRegistroEditar.getText().trim().isEmpty() || 
            ModuloRegistroEditar.getSelectedItem() == null || 
            HabitacionRegistroEditar.getSelectedItem() == null) {
            
            JOptionPane.showMessageDialog(this, "Por favor, todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int matricula = Integer.parseInt(MatriculaRegistroEditar.getText().trim());
        String nombres = NombresRegistroEditar.getText().trim();
        String apellidos = ApellidosRegistroEditar.getText().trim();
        String telefono = NumeroRegistroEditar.getText().trim();
        String modulo = ModuloRegistroEditar.getSelectedItem().toString().trim();
        String habitacion = HabitacionRegistroEditar.getSelectedItem().toString().trim();

        try {
            estudianteControlador.actualizarEstudiante(matricula, nombres, apellidos, telefono, modulo, habitacion);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EditarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_GuardarEstudiantebtnActionPerformed

    private void EditarEstudiantebtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEstudiantebtn2MouseEntered
        EditarEstudiantebtn2.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_EditarEstudiantebtn2MouseEntered

    private void EditarEstudiantebtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEstudiantebtn2MouseExited
        EditarEstudiantebtn2.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_EditarEstudiantebtn2MouseExited

    private void EditarEstudiantebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEstudiantebtn2ActionPerformed
        EditarEstudiante editarEstudiante = new EditarEstudiante();
        editarEstudiante.setVisible(true);
        this.dispose();

        editarEstudiante.setLocationRelativeTo(null);

        DefaultTableModel modelo = (DefaultTableModel) editarEstudiante.TablaEstudiantesEditar.getModel();
        estudianteControlador.MostrarEstudiante(modelo);
    }//GEN-LAST:event_EditarEstudiantebtn2ActionPerformed

    private void MatriculaRegistroEditarNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaRegistroEditarNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculaRegistroEditarNewActionPerformed

    private void MatriculaRegistroEditarNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MatriculaRegistroEditarNewKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculaRegistroEditarNewKeyTyped

    private void VerEstudianteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerEstudianteBtnMouseEntered
        VerEstudianteBtn.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_VerEstudianteBtnMouseEntered

    private void VerEstudianteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerEstudianteBtnMouseExited
        VerEstudianteBtn.setBackground(new Color(20,101,187));
    }//GEN-LAST:event_VerEstudianteBtnMouseExited

    private void RegistrarEstudianteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarEstudianteBtnMouseEntered
        RegistrarEstudianteBtn.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_RegistrarEstudianteBtnMouseEntered

    private void HistorialCocinaBntMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialCocinaBntMouseEntered
        HistorialCocinaBnt.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_HistorialCocinaBntMouseEntered

    private void HistorialCocinaBntMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialCocinaBntMouseExited
        HistorialCocinaBnt.setBackground(new Color(20,101,187));
    }//GEN-LAST:event_HistorialCocinaBntMouseExited

    private void HistorialEntradaSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialEntradaSalidaMouseEntered
        HistorialEntradaSalida.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_HistorialEntradaSalidaMouseEntered

    private void InformeDeActividadBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformeDeActividadBtnMouseEntered
        InformeDeActividadBtn.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_InformeDeActividadBtnMouseEntered

    private void InformeDeActividadBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformeDeActividadBtnMouseExited
        InformeDeActividadBtn.setBackground(new Color(20,101,187));
    }//GEN-LAST:event_InformeDeActividadBtnMouseExited

    private void HistorialBotellonesbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialBotellonesbtnMouseEntered
        HistorialBotellonesbtn.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_HistorialBotellonesbtnMouseEntered

    private void HistorialBotellonesbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialBotellonesbtnMouseExited
        HistorialBotellonesbtn.setBackground(new Color(20,101,187));
    }//GEN-LAST:event_HistorialBotellonesbtnMouseExited

    private void NotificacionesBotellonesbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificacionesBotellonesbtnMouseEntered
       NotificacionesBotellonesbtn.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_NotificacionesBotellonesbtnMouseEntered

    private void NotificacionesBotellonesbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificacionesBotellonesbtnMouseExited
        NotificacionesBotellonesbtn.setBackground(new Color(20,101,187));
    }//GEN-LAST:event_NotificacionesBotellonesbtnMouseExited

    private void RetirarEstudiantesbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarEstudiantesbtnMouseEntered
        RetirarEstudiantesbtn.setBackground(new Color(0,55,133));
    }//GEN-LAST:event_RetirarEstudiantesbtnMouseEntered

    private void RetirarEstudiantesbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarEstudiantesbtnMouseExited
        RetirarEstudiantesbtn.setBackground(new Color(20,101,187));
    }//GEN-LAST:event_RetirarEstudiantesbtnMouseExited

    private void HistorialEntradaSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialEntradaSalidaMouseExited
        HistorialEntradaSalida.setBackground(new Color(20,101,187));
    }//GEN-LAST:event_HistorialEntradaSalidaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosRegistroEditar;
    private javax.swing.JTextField BuscarMatriculaFieldEditar;
    private javax.swing.JButton CargarEstudiantebtn;
    private javax.swing.JButton EditarEstudiantebtn2;
    private javax.swing.JButton GuardarEstudiantebtn;
    private javax.swing.JComboBox<String> HabitacionRegistroEditar;
    private javax.swing.JButton HistorialBotellonesbtn;
    private javax.swing.JButton HistorialCocinaBnt;
    private javax.swing.JButton HistorialEntradaSalida;
    private javax.swing.JButton InformeDeActividadBtn;
    private javax.swing.JTextField MatriculaRegistroEditar;
    private javax.swing.JTextField MatriculaRegistroEditarNew;
    private javax.swing.JComboBox<String> ModuloRegistroEditar;
    private javax.swing.JTextField NombresRegistroEditar;
    private javax.swing.JButton NotificacionesBotellonesbtn;
    private javax.swing.JTextField NumeroRegistroEditar;
    private javax.swing.JButton RegistrarEstudianteBtn;
    private javax.swing.JButton RetirarEstudiantesbtn;
    public javax.swing.JTable TablaEstudiantesEditar;
    private javax.swing.JButton VerEstudianteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables

    private EditarEstudiante(DefaultTableModel modelo, String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
